name: youtube_reporter
description: YouTube reporter is an app which main purpose is to make it easier to report abuse of videos that provokes violece/war/russian propaganda/terrorism.
version: 1.5.0+25

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # System
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.0

  # Storage
  shared_preferences: ^2.0.13

  # Auth
  google_sign_in: ^5.2.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.4

  # APIs
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  googleapis: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/